version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: dashboard_ai_postgres
    environment:
      POSTGRES_DB: dashboard_ai
      POSTGRES_USER: dashboard_user
      POSTGRES_PASSWORD: dashboard_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dashboard_ai_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: dashboard_ai_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@dashboardai.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - dashboard_ai_network

volumes:
  postgres_data:

networks:
  dashboard_ai_network:
    driver: bridge
